### PR TITLE
Create pseudobulk.py

### PR DESCRIPTION
**Pull request by hopedisastro**
This script performs pseudobulk (mean aggregation) of an input AnnData object
Prior to pseudobulking, the following steps are performed:
- Remove cells with no counts
- Normalisation
- Log transformation (ln(1+x))
- Batch correction using ComBat

Output is a TSV file by cell-type. Each row is a sample and each column is a gene.

### CODE REVIEW

**Comment by hopedisastro** [comment]
my `black` is not `blacking`

**Comment by hopedisastro** [comment]
Successful batch: https://batch.hail.populationgenomics.org.au/batches/434056/jobs/1

**Comment by hopedisastro** [comment]
The file in `main` is 140GB. The `test` file was ~250MB and peak storage ended up ~500MB. 
Is this ok, or do we need to optimise the script further?

**Review by MattWellie — APPROVED** [review]
I've added a method docstring and passed the linting checks, feel free to merge if you approve!

**Pull request merged**
